version: '3.4'
services:
  postgres:
    image: postgres
    container_name: srv_postgres
    volumes:
      - '/home/jorge-n/ambiente_de_testes/var/lib/postgres:/var/lib/postgresql/'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB= database_padrao
      - POSTGRES_PASSWORD= 'senha_super_forte'
      - POSTGRES_USER= usuario_db
      - PGPORT=5432
  nginx:
    image: nginx
    container_name: srv_nginx
    volumes:
      - '/home/jorge-n/ambiente_de_testes/nginx/www:/usr/share/nginx/html/'
    ports:
      - '81:80'
    environment:
      - NGINX_HOST=ambiente_de_testes.com
      - NGINX_PORT=80
  node:
    image: 'node:slim'
    container_name: srv_node
    depends_on:
      - postgres
    volumes:
      - '/home/jorge-n/ambiente_de_testes/backend/node:/home/node/app'
    ports:
      - '3001:3001'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=homolog
      - PORT=3001
      - SESSION_SECRET=5cb31cf941ca1bb307844b51b8223c96
      - DB_URI=postgres
      - DB_USER=root
      - DB_PASSWORD=senha_super_forte
      - DB_DATABASE=database_padrao
    expose:
      - '3001'
    command: bash -c "npm install && node src/server.js"
volumes:
  postgres: {}
  www: {}
  node: {}
